# Generated by Django 4.1 on 2022-09-05 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options_alter_category_slug_and_more'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ['-published']},
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='category',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='HitDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogmodel')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ipaddressmodel')),
            ],
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='hit',
            field=models.ManyToManyField(through='blog.HitDate', to='blog.ipaddressmodel'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
