# Generated by Django 4.1 on 2022-09-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_ipaddressmodel_alter_blogmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='is_publish',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده'), ('i', 'در حال بررسب'), ('b', 'نیاز به بررسی بیشتر')], default='d', max_length=1),
        ),
    ]
