# Generated by Django 4.0.2 on 2022-02-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_articles_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='مقاله ویژه'),
        ),
    ]
